reclamation_reclamation:
    resource: "@ReclamationBundle/Resources/config/routing/reclamation.yml"
    prefix:   /reclamation

reclamation_typereclamation:
    resource: "@ReclamationBundle/Resources/config/routing/typereclamation.yml"
    prefix:   /typereclamation

reclamation:
    path:     /reclama
    defaults: { _controller: ReclamationBundle:Default:reclamation }
