reclamation_index:
    path:     /index
    defaults: { _controller: "ReclamationBundle:Reclamation:index" }
    methods:  GET

reclamation_list:
    path:     /index
    defaults: { _controller: "ReclamationBundle:Reclamation:list" }
    methods:  GET

corbeille:
    path:     /corbeille
    defaults: { _controller: "ReclamationBundle:Reclamation:corbeille" }
    methods:  GET

archive:
    path:     /archive
    defaults: { _controller: "ReclamationBundle:Reclamation:archive" }
    methods:  GET

reclamation_show:
    path:     /{id}/show
    defaults: { _controller: "ReclamationBundle:Reclamation:show" }
    methods:  GET

reclamation_showBo:
    path:     /{id}/showBo
    defaults: { _controller: "ReclamationBundle:Reclamation:showBo" }
    methods:  GET

reclamation_new:
    path:     /new
    defaults: { _controller: "ReclamationBundle:Reclamation:new" }
    methods:  [GET, POST]

reclamation_edit:
    path:     /{id}/edit
    defaults: { _controller: "ReclamationBundle:Reclamation:edit" }
    methods:  [GET, POST]

reclamation_delete:
    path:     /{id}/delete
    defaults: { _controller: "ReclamationBundle:Reclamation:delete" }
    methods:  DELETE

toCorbeille:
    path:     /{id}/toCorbeille
    defaults: { _controller: "ReclamationBundle:Reclamation:toCorbeille" }
    methods:  GET

restaurerCorb:
    path:     /{id}/restaurer
    defaults: { _controller: "ReclamationBundle:Reclamation:restaurerCorb" }
    methods:  GET

deleteCorb:
    path:     /{id}/delete
    defaults: { _controller: "ReclamationBundle:Reclamation:deleteCorb" }
    methods:  GET

toArchive:
    path:    /{id}/toArchive
    defaults: { _controller: "ReclamationBundle:Reclamation:toArchive" }
    methods:  GET

restaurerArch:
    path:     /{id}/restaurer
    defaults: { _controller: "ReclamationBundle:Reclamation:restaurerArch" }
    methods:  GET