eventtype_index:
    path:     /
    defaults: { _controller: "EventBundle:eventtype:index" }
    methods:  GET

eventtype_show:
    path:     /{id}/show
    defaults: { _controller: "EventBundle:eventtype:show" }
    methods:  GET

eventtype_new:
    path:     /new
    defaults: { _controller: "EventBundle:eventtype:new" }
    methods:  [GET, POST]

eventtype_edit:
    path:     /{id}/edit
    defaults: { _controller: "EventBundle:eventtype:edit" }
    methods:  [GET, POST]

eventtype_delete:
    path:     /{id}/delete
    defaults: { _controller: "EventBundle:eventtype:delete" }
    methods:  DELETE
