event_eventtype:
    resource: "@EventBundle/Resources/config/routing/eventtype.yml"
    prefix:   /bo/eventtype

event_review:
  resource: "@EventBundle/Resources/config/routing/review.yml"
  prefix:   /review

event_events:
  resource: "@EventBundle/Resources/config/routing/event.yml"
  prefix:   /events
