categorieforum_index:
    path:     /
    defaults: { _controller: "CommunicationBundle:CategorieForum:index" }
    methods:  GET

categorieforum_show:
    path:     /{id}/show
    defaults: { _controller: "CommunicationBundle:CategorieForum:show" }
    methods:  GET

categorieforum_new:
    path:     /new
    defaults: { _controller: "CommunicationBundle:CategorieForum:new" }
    methods:  [GET, POST]

categorieforum_edit:
    path:     /{id}/edit
    defaults: { _controller: "CommunicationBundle:CategorieForum:edit" }
    methods:  [GET, POST]

categorieforum_delete:
    path:     /{id}/delete
    defaults: { _controller: "CommunicationBundle:CategorieForum:delete" }
    methods:  DELETE
